trigger:
  branches:
    include:
      - main

pool: appagent

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.14.7'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    backendServiceArm: 'myconnection'
    backendAzureRmResourceGroupName: 'gss-rg'
    backendAzureRmStorageAccountName: 'gssstg'
    backendAzureRmContainerName: 'gsscont'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    environmentServiceNameAzureRM: 'myconnection'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'myconnection'