trigger:
  branches:
    include:
      - main

pool: autoagent

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    backendServiceArm: 'myconnection'
    backendAzureRmResourceGroupName: 'rg-vishnu001'
    backendAzureRmStorageAccountName: 'stgvishnu'
    backendAzureRmContainerName: 'contvishnu'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    environmentServiceNameAzureRM: 'myconnection'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'myconnection'