trigger:
  branches:
    include:
      - main

pool: appagent  # Pool name define

stages:
  - stage: initplan
    displayName: Init & Plan
    jobs:
      - job: initplan
        displayName: Init & Plan

        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.14.7'
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
            backendServiceArm: 'myconnection'
            backendAzureRmResourceGroupName: 'gss-rg'
            backendAzureRmStorageAccountName: 'gssstg'
            backendAzureRmContainerName: 'gsscont'
            backendAzureRmKey: 'terraform.tfstate'

        # - task: PowerShell@2
        #   inputs:
        #     targetType: 'inline'
        #     script: 'Invoke-WebRequest https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.ps1 -OutFile install.ps1.\install.ps1'

        # - task: PowerShell@2
        #   inputs:
        #     targetType: 'inline'
        #     script: |
        #       infracost configure set api_key $(INFRACOST_API_KEY)
        #           infracost breakdown --path tfplan.binary --format table


        - task: PowerShell@2
          displayName: Tflint Scanning
          inputs:
            targetType: 'inline'
            script: |
              Invoke-WebRequest https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip -OutFile tflint.zip
              Expand-Archive tflint.zip -DestinationPath tflint
              .\tflint\tflint.exe --init
              .\tflint\tflint.exe
        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
            environmentServiceNameAzureRM: 'myconnection'
          
  - stage: securityscanning
    displayName: Security Scanning
    jobs:
      - job: securityscanning
        displayName: Security Scanning
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)'
        
  - stage: manualapprover
    displayName: Manual Approver
    jobs:
      - job: manualapprover
        displayName: Manual Approver
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'vishnukantmishra21072002@gmail.com'
            approvers: 'vishnukantmishra21072002@gmail.com'

  - stage: initapply
    displayName: Init & Apply
    jobs:
      - job: initandapply
        displayName: Init & Apply
        steps:
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
            backendServiceArm: 'myconnection'
            backendAzureRmResourceGroupName: 'gss-rg'
            backendAzureRmStorageAccountName: 'gssstg'
            backendAzureRmContainerName: 'gsscont'
            backendAzureRmKey: 'terraform.tfstate'
        
        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'myconnection'